// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGEMOnline.Data.Context;

namespace SGEMOnline.Data.Migrations
{
    [DbContext(typeof(SGEMOnlineDBContext))]
    partial class SGEMOnlineDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SGEMOnline.Business.Models.Item", b =>
                {
                    b.Property<Guid>("Codigo")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<DateTime>("DataCadastro");

                    b.Property<string>("Descricao");

                    b.Property<double>("Estoque");

                    b.Property<string>("Imagem");

                    b.Property<decimal>("Preco");

                    b.HasKey("Codigo");

                    b.ToTable("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
